# config.yaml
d_model: 1024
num_heads: 16
d_ff: 1344
rope_theta: 10000
num_layers: 4
vocab_size: 32000

eps: 1e-8
betas: [0.9, 0.999]
lr: 2e-3
weight_decay: 0.01

# batch_size * num_iters = 1,280,000
context_length: 512
batch_size: 64
num_iterations: 200000

log_freq: 100
val_freq: 500
ckpt_freq: 1000

train_data: "/home/c-aalag/results/new_encoded_owt_train.npy"
val_data: "/home/c-aalag/results/encoded_owt_valid.txt.npy"
ckpt_dir: "/home/c-aalag/results/checkpoints"

no_cuda: false

# Additional wandb settings:
use_wandb: true
project: "tinystories_expts"
experiment_name: "owt_1024_2e3"